#!/usr/bin/env python3
import subprocess


from urllib.request import urlopen
import json

url = "https://api.github.com/orgs/galasa-dev/repos"
response = urlopen(url)
data_raw = response.read().decode("utf-8")
repositories_details = json.loads(data_raw)
data_pretty = json.dumps(repositories_details, indent=4)


for repo_details in repositories_details:
    #print (json.dumps(repo_details, indent=4))
    repo_name = repo_details['name']
    
    # Remove the folder for the repo.
    print( f"Deleting {repo_name}" )
    subprocess.run(["rm","-fr" , repo_name ] , check=True )

    print( f"Cloning {repo_name}" )
    subprocess.run(["git", "clone" , f'https://github.com/galasa-dev/{repo_name}'], check=True)
